### ISSUE TITLE
Bug: commandd does not add new functions when original serverless.yml does not contain `functions`

### ISSUE THREAD

**Issue by Shpionus** [Reckon-Limited/serverless_swagger#7]
serverless.yml

```yml
service: node-swagger

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless_swagger

custom:
  swagger_file: swagger.yml

provider:
  name: aws
  runtime: nodejs18.x
  ```

`sls swagger` creates new js files and updates `serverless.yml` ( removes comments and extra new lines ) but does not add new functions.
